# Use a imagem oficial do Node.js (versão LTS)
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de package para instalar dependências
COPY package*.json ./

# Instala as dependências
RUN npm install --production

# Copia o restante do código para dentro do container
COPY . .

# Expõe a porta que o app vai rodar (exemplo 3000)
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["node", "server.js"]
